name: Release linux package
run-name:
on: [push]
jobs:
  package linux packages and upload packages:
    runs-on: ubuntu-latest
    jobs:
    - uses: actions/checkout@v2
      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: x86_64-unknown-linux-gnu
            override: true
            components: rustfmt, clippy
            - name: install lib
                  run: sudo apt install nala -y
                       sudo nala update -y
                       sudo nala upgrade -y
                       sudo nala install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libappindicator3-dev librsvg2-dev  libjavascriptcoregtk-4.0-18 libsoup2.4-dev -y

          - name: packaging linux packages
                run: yarn tauri build


          - name: upload  AppImage
          - uses: actions/upload-artifact@v3
            with:
              name: linux-packages
              path: src-tauri/target/release/bundle/appimage/*.AppImage

          - name: upload  deb
          - uses: actions/upload-artifact@v3
            with:
              name: linux-packages
              path: src-tauri/target/release/bundle/deb/*.deb
